PASS = ""
CHANNEL = ""
HOST = "irc.freenode.net"
PORT = 6667
NICK = "wolfbot"
OWNER = "unaffiliated/wolfbot_admin1"
ADMINS = ("unaffiliated/wolfbot_admin1", "unaffiliated/wolfbot_admin2")
CMD_CHAR = "!"
CHANGING_HOST_QUIT_MESSAGE = "Changing host"