PASS = ""
CHANNEL = ""
HOST = "irc.freenode.net"
PORT = 6667
NICK = "wolfbot"
OWNERS = ("unaffiliated/wolfbot_admin1",)  # the comma is required at the end if there is one owner
ADMINS = ("unaffiliated/wolfbot_admin2", "unaffiliated/wolfbot_admin3")
CMD_CHAR = "!"
CHANGING_HOST_QUIT_MESSAGE = "Changing host"
DEBUG_MODE = False